### ISSUE TITLE
Crownstone Homey App | Update to 2.0 version

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-homey#1]
Current error:

```
2019-01-23 18:13:39 [log] [ManagerDrivers] [crownstone] [2] I can't find this Crownstone cuz I got an error :( TypeError: Cannot read property 'localName' of undefined
    at new BleAdvertisement (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/BleAdvertisement.js:1:369)
    at ManagerBLE.__createAdvertisementInstance (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/ble.js:1:1220)
    at __advertisementsByPeripheralUUID.(anonymous function).__client.emit.then.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/ble.js:1:1089)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019-01-23 18:13:39 [log] [ManagerDrivers] [crownstone] [2] Catch and reject TypeError: Cannot read property 'localName' of undefined
    at new BleAdvertisement (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/BleAdvertisement.js:1:369)
    at ManagerBLE.__createAdvertisementInstance (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/ble.js:1:1220)
    at __advertisementsByPeripheralUUID.(anonymous function).__client.emit.then.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/ble.js:1:1089)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by mrquincle** [comment]
Ah, apparently this is an open-standing issue at Homey / Athom itself: https://github.com/athombv/homey-apps-sdk-issues/issues/7

**Comment by mrquincle** [comment]
This bug has been fixed.
